version: "3.9"
services:
  app:
    container_name: ${PROJECT}_app
    build: 
      context: .
    ports: 
      - ${APP_PORT}:80
    volumes: 
      - ..:/workspace
      - ../app:/var/www/html
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  database:
    container_name: ${PROJECT}_database
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT}_phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      -  ${PMA_APP_PORT}:80